In [6]:
import numpy as np
import math

In [11]:
def mu(i):
    return i % 3
def nu(i):
    return math.floor(i / 3)

In [17]:
G = np.array(
    [[7,-8,1],
    [-8,16,-8],
    [1,-8,7]])
M = np.array(
    [[4,2,-1],
    [2,16,2],
    [-1,2,4]])

G1 = np.zeros((6,6))
G2 = np.zeros((6,6))
M1 = np.zeros((6,6))

for i in range(6):
    for j in range(6):
        G1[i][j] = G[mu(i)][mu(j)] * M[nu(i)][nu(j)]
        G2[i][j] = M[mu(i)][mu(j)] * G[nu(i)][nu(j)]
        M1[i][j] = M[mu(i)][mu(j)] * M[nu(i)][nu(j)]

print(G1, "\n")
print(G2, "\n")
print(M1, "\n")

[[  28.  -32.    4.   14.  -16.    2.]
 [ -32.   64.  -32.  -16.   32.  -16.]
 [   4.  -32.   28.    2.  -16.   14.]
 [  14.  -16.    2.  112. -128.   16.]
 [ -16.   32.  -16. -128.  256. -128.]
 [   2.  -16.   14.   16. -128.  112.]] 

[[  28.   14.   -7.  -32.  -16.    8.]
 [  14.  112.   14.  -16. -128.  -16.]
 [  -7.   14.   28.    8.  -16.  -32.]
 [ -32.  -16.    8.   64.   32.  -16.]
 [ -16. -128.  -16.   32.  256.   32.]
 [   8.  -16.  -32.  -16.   32.   64.]] 

[[ 16.   8.  -4.   8.   4.  -2.]
 [  8.  64.   8.   4.  32.   4.]
 [ -4.   8.  16.  -2.   4.   8.]
 [  8.   4.  -2.  64.  32. -16.]
 [  4.  32.   4.  32. 256.  32.]
 [ -2.   4.   8. -16.  32.  64.]] 

